DROP DATABASE IF EXISTS cotekcon_db;

CREATE DATABASE cotekcon_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE cotekcon_db;

CREATE TABLE PHONGBAN (
    MaPB VARCHAR(10) PRIMARY KEY,
    TenPB VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE CHUCVU (
    MaCVu VARCHAR(10) PRIMARY KEY,
    TenCVu VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE TRINHDO (
    MaTD VARCHAR(10) PRIMARY KEY,
    TenTD VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE LUONG (
    MaLuong VARCHAR(10) PRIMARY KEY,
    LuongCoBan DECIMAL(15,2) NOT NULL CHECK (LuongCoBan >= 0),
    PhuCap DECIMAL(15,2) NOT NULL CHECK (PhuCap >= 0),
    LamThem DECIMAL(15,2) NOT NULL CHECK (LamThem >= 0),
    Thuong DECIMAL(15,2) NOT NULL CHECK (Thuong >= 0),
    KhauTru DECIMAL(15,2) NOT NULL CHECK (KhauTru >= 0)
) ENGINE=InnoDB;

CREATE TABLE CHUDTU (
    MaChuDT VARCHAR(10) PRIMARY KEY,
    TenDoanhNghiep VARCHAR(100) NOT NULL,
    MaSoThue VARCHAR(20) UNIQUE,
    TenNDD VARCHAR(100) NOT NULL,
    ChucDanhNDD VARCHAR(50),
    Email_LH VARCHAR(100) NOT NULL UNIQUE CHECK (Email_LH LIKE '%@%'),
    QuocGia VARCHAR(50) NOT NULL,
    Tinh VARCHAR(50),
    Phuong VARCHAR(50),
    DiaChi_ChiTiet VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE VAITRO_DA (
    MaVT VARCHAR(10) PRIMARY KEY,
    TenVT VARCHAR(50) NOT NULL,
    MoTa VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE DANHMUC_VATTU (
    MaVTu VARCHAR(10) PRIMARY KEY,
    TenVTu VARCHAR(100) NOT NULL,
    DonViTinh VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(100) NOT NULL,
    QuocGia VARCHAR(50) NOT NULL,
    DiaChi_ChiTiet VARCHAR(200),
    Email_LH VARCHAR(100) NOT NULL UNIQUE CHECK (Email_LH LIKE '%@%')
) ENGINE=InnoDB;

-- =============== PHẦN 2: BẢNG CÓ FK TỪ BẢNG CHA ===============

CREATE TABLE DUAN (
    MaDA VARCHAR(10) PRIMARY KEY,
    MaChuDT VARCHAR(10) NOT NULL,
    TenDA VARCHAR(100) NOT NULL,
    QuocGia VARCHAR(50) NOT NULL,
    Tinh VARCHAR(50),
    Phuong VARCHAR(50),
    DiaChi_ChiTiet VARCHAR(200),
    NgayBD DATE NOT NULL,
    NgayKTDuKien DATE,
    NgayKTThucTe DATE,
    NganSach DECIMAL(18,2) NOT NULL CHECK (NganSach >= 0),
    FOREIGN KEY (MaChuDT) REFERENCES CHUDTU(MaChuDT),
    CONSTRAINT chk_NgayKT_DuKien CHECK (NgayKTDuKien >= NgayBD),
    CONSTRAINT chk_NgayKT_ThucTe CHECK (NgayKTThucTe >= NgayBD)
) ENGINE=InnoDB;

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    CCCD VARCHAR(12) NOT NULL UNIQUE CHECK (CHAR_LENGTH(CCCD) = 12),
    Ho VARCHAR(50) NOT NULL,
    TenDem VARCHAR(50),
    Ten VARCHAR(50) NOT NULL,
    NgaySinh DATE,
    GioiTinh VARCHAR(10) CHECK (GioiTinh IN ('nam', 'nữ', 'khác')),
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE CHECK (Email LIKE '%@%'),
    NgayVaoLam DATE NOT NULL,
    MaPB VARCHAR(10) NOT NULL,
    FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB)
) ENGINE=InnoDB;

-- =============== PHẦN 3: BẢNG LIÊN KẾT / PHỤ THUỘC NHIỀU BẢNG ===============

CREATE TABLE PHANCONG_CHUCVU (
    MaNV VARCHAR(10),
    MaPB VARCHAR(10),
    MaCVu VARCHAR(10),
    NgayBatDau DATE,
    GhiChu VARCHAR(200),
    PRIMARY KEY (MaNV, MaPB, MaCVu),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB),
    FOREIGN KEY (MaCVu) REFERENCES CHUCVU(MaCVu)
) ENGINE=InnoDB;

CREATE TABLE TRINHDO_NV (
    MaNV VARCHAR(10),
    MaTD VARCHAR(10),
    NgayCap DATE NOT NULL,
    NgayHetHan DATE,
    GhiChu VARCHAR(200),
    PRIMARY KEY (MaNV, MaTD, NgayCap),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaTD) REFERENCES TRINHDO(MaTD)
) ENGINE=InnoDB;

CREATE TABLE HOPDONG (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaDA VARCHAR(10) NOT NULL,
    NgayKy DATE NOT NULL,
    GiaTri DECIMAL(18,2) NOT NULL CHECK (GiaTri >= 0),
    DieuKhoan VARCHAR(500),
    ChiTiet_HopDong TEXT,
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA)
) ENGINE=InnoDB;

CREATE TABLE THANHTOAN (
    MaTT VARCHAR(10) PRIMARY KEY,
    MaHD VARCHAR(10) NOT NULL,
    NgayThanhToan DATE NOT NULL,
    SoTien DECIMAL(18,2) NOT NULL CHECK (SoTien >= 0),
    FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD)
) ENGINE=InnoDB;

CREATE TABLE PHANCONG_DUAN (
    MaNV VARCHAR(10),
    MaDA VARCHAR(10),
    MaVT VARCHAR(10),
    SoGioDuKien INT CHECK (SoGioDuKien > 0),
    NgayBatDau DATE,
    GhiChu VARCHAR(200),
    PRIMARY KEY (MaNV, MaDA, MaVT),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA),
    FOREIGN KEY (MaVT) REFERENCES VAITRO_DA(MaVT)
) ENGINE=InnoDB;

CREATE TABLE CHAMCONG (
    MaNV VARCHAR(10),
    Ngay DATE,
    MaDA VARCHAR(10),
    SoPhutLam INT NOT NULL CHECK (SoPhutLam > 0),
    PRIMARY KEY (MaNV, Ngay, MaDA),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA)
) ENGINE=InnoDB;

CREATE TABLE NHANVIEN_LUONG (
    MaNV VARCHAR(10) PRIMARY KEY,
    MaLuong VARCHAR(10) NOT NULL UNIQUE,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaLuong) REFERENCES LUONG(MaLuong)
) ENGINE=InnoDB;

CREATE TABLE TT_LUONG (
    MaNV VARCHAR(10),
    Thang INT CHECK (Thang BETWEEN 1 AND 12),
    Nam INT,
    LuongCoBan DECIMAL(15,2) NOT NULL CHECK (LuongCoBan >= 0),
    PhuCap DECIMAL(15,2) NOT NULL CHECK (PhuCap >= 0),
    LamThem DECIMAL(15,2) NOT NULL CHECK (LamThem >= 0),
    Thuong DECIMAL(15,2) NOT NULL CHECK (Thuong >= 0),
    KhauTru DECIMAL(15,2) NOT NULL CHECK (KhauTru >= 0),
    PRIMARY KEY (MaNV, Thang, Nam),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
) ENGINE=InnoDB;

CREATE TABLE SUDUNG_VATTU (
    MaSDVT VARCHAR(10) PRIMARY KEY,
    MaDA VARCHAR(10) NOT NULL,
    MaVTu VARCHAR(10) NOT NULL,
    SoLuongSuDung DECIMAL(12,2) NOT NULL CHECK (SoLuongSuDung > 0),
    MaNCC VARCHAR(10) NOT NULL,
    DonGiaApDung DECIMAL(15,2) NOT NULL CHECK (DonGiaApDung >= 0),
    NgayMua DATE,
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA),
    FOREIGN KEY (MaVTu) REFERENCES DANHMUC_VATTU(MaVTu),
    FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
) ENGINE=InnoDB;

CREATE TABLE BAOCAO_TIENDO (
    MaBC VARCHAR(10) PRIMARY KEY,
    MaDA VARCHAR(10) NOT NULL,
    NgayLap DATE NOT NULL,
    TyLeHT DECIMAL(5,2) NOT NULL CHECK (TyLeHT BETWEEN 0 AND 100),
    MoTaNgan VARCHAR(200) NOT NULL,
    GhiChu VARCHAR(500),
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA)
) ENGINE=InnoDB;