DROP DATABASE IF EXISTS cotekcon_db;
CREATE DATABASE cotekcon_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cotekcon_db;

SET default_storage_engine = InnoDB;
SET NAMES utf8mb4;
SET COLLATION_CONNECTION = 'utf8mb4_unicode_ci';

CREATE TABLE PHONGBAN (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaPB VARCHAR(20) NOT NULL UNIQUE,
    TenPB VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(255)
);

CREATE TABLE CHUCVU (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaCVu VARCHAR(20) NOT NULL UNIQUE,
    TenCVu VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(255)
);

CREATE TABLE TRINHDO (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaTD VARCHAR(20) NOT NULL UNIQUE,
    TenTD VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(255)
);

CREATE TABLE CHUDTU (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaChuDT VARCHAR(20) NOT NULL UNIQUE,
    TenDoanhNghiep VARCHAR(100) NOT NULL,
    MaSoThue VARCHAR(25) UNIQUE,
    TenNDD VARCHAR(150) NOT NULL,
    ChucDanhNDD VARCHAR(100),
    Email VARCHAR(255),
    QuocGia VARCHAR(80),
    Tinh VARCHAR(80),
    Phuong VARCHAR(80),
    DiaChi_ChiTiet VARCHAR(255)
);

CREATE TABLE VAITRO_DA (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaVT VARCHAR(20) NOT NULL UNIQUE,
    TenVT VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(255)
);

CREATE TABLE DANHMUC_VATTU (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaVTu VARCHAR(20) NOT NULL UNIQUE,
    TenVTu VARCHAR(100) NOT NULL UNIQUE,
    DonViTinh VARCHAR(80)
);

CREATE TABLE NHACUNGCAP (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaNCC VARCHAR(20) NOT NULL UNIQUE,
    TenNCC VARCHAR(100) NOT NULL,
    QuocGia VARCHAR(80),
    DiaChi_ChiTiet VARCHAR(255),
    Email VARCHAR(255)
);

CREATE TABLE NHANVIEN (
    id INT PRIMARY KEY AUTO_INCREMENT,
    MaNV VARCHAR(20) NOT NULL UNIQUE,
    CCCD VARCHAR(25) UNIQUE,
    Ho VARCHAR(50) NOT NULL,
    TenDem VARCHAR(50),
    Ten VARCHAR(50) NOT NULL,
    NgaySinh DATE,
    GioiTinh VARCHAR(25),
    SDT VARCHAR(25) UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    NgayVaoLam DATE,
    id_PHONGBAN INT,
    FOREIGN KEY (id_PHONGBAN)
        REFERENCES PHONGBAN (id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT check_NHANVIEN_ngayvaolam_hople CHECK (NgaySinh IS NULL OR NgayVaoLam IS NULL
        OR NgayVaoLam > NgaySinh)
);

CREATE TABLE PHANCONG_CHUCVU (
    id_NHANVIEN INT,
    id_PHONGBAN INT,
    id_CHUCVU INT,
    NgayBatDau DATE,
    GhiChu VARCHAR(255),
    PRIMARY KEY (id_NHANVIEN , id_PHONGBAN , id_CHUCVU),
    FOREIGN KEY (id_NHANVIEN)
        REFERENCES NHANVIEN (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_PHONGBAN)
        REFERENCES PHONGBAN (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_CHUCVU)
        REFERENCES CHUCVU (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TRINHDO_NV (
    id_NHANVIEN INT,
    id_TRINHDO INT,
    NgayCap DATE,
    NgayHetHan DATE,
    GhiChu VARCHAR(255),
    PRIMARY KEY (id_NHANVIEN, id_TRINHDO, NgayCap),
    FOREIGN KEY (id_NHANVIEN) REFERENCES NHANVIEN(id),
    FOREIGN KEY (id_TRINHDO) REFERENCES TRINHDO(id),
    CONSTRAINT check_TRINHDO_NV_ngayhethan_hople CHECK (NgayHetHan IS NULL
        OR NgayHetHan >= NgayCap)
);

CREATE TABLE DUAN (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaDA VARCHAR(20) NOT NULL UNIQUE,
    id_CHUDTU INT NOT NULL,
    TenDA VARCHAR(100) NOT NULL,
    QuocGia VARCHAR(80),
    Tinh VARCHAR(80),
    Phuong VARCHAR(80),
    DiaChi_ChiTiet VARCHAR(255),
    NgayBatDau DATE,
    NgayKTDuKien DATE,
    NgayKTThucTe DATE,
    NganSach DECIMAL(15, 0) CHECK ( NganSach >= 0 ),
    FOREIGN KEY (id_CHUDTU) REFERENCES CHUDTU(id),
    CONSTRAINT check_DUAN_ngayKTTDuKien_hople CHECK (NgayBatDau IS NULL OR NgayKTDuKien IS NULL OR NgayKTDuKien >= NgayBatDau),
    CONSTRAINT check_DUAN_ngayKTThucTe_hople CHECK (NgayBatDau IS NULL OR NgayKTDuKien IS NULL OR  NgayKTThucTe >= NgayBatDau)
);

CREATE TABLE CHAMCONG (
	id_NHANVIEN INT,
    Ngay DATE,
    id_DUAN INT,
    SoPhutLam SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id_NHANVIEN, Ngay, id_DUAN),
    FOREIGN KEY (id_NHANVIEN) REFERENCES NHANVIEN(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_DUAN) REFERENCES DUAN(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LUONG_NV (
	id_NHANVIEN INT PRIMARY KEY,
    LuongCoBan DECIMAL(15, 0) CHECK ( LuongCoBan >= 0 ),
    PhuCap DECIMAL(15, 0) CHECK ( PhuCap >= 0 ),
    LamThem DECIMAL(15, 0) CHECK ( LamThem >= 0 ),
    Thuong DECIMAL(15, 0) CHECK ( Thuong >= 0 ),
    KhauTru DECIMAL(15, 0),
    FOREIGN KEY (id_NHANVIEN) REFERENCES NHANVIEN(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TT_LUONG (
	id_NHANVIEN INT,
    Thang TINYINT CHECK (Thang BETWEEN 1 AND 12),
    Nam SMALLINT UNSIGNED,
    LuongCoBan DECIMAL(15, 0) CHECK ( LuongCoBan >= 0 ),
    PhuCap DECIMAL(15, 0) CHECK ( PhuCap >= 0 ),
    LamThem DECIMAL(15, 0) CHECK ( LamThem >= 0 ),
    Thuong DECIMAL(15, 0) CHECK ( Thuong >= 0 ),
    KhauTru DECIMAL(15, 0),
    PRIMARY KEY (id_NHANVIEN, Thang, Nam),
    FOREIGN KEY (id_NHANVIEN) REFERENCES NHANVIEN(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HOPDONG (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaHD VARCHAR(20) NOT NULL UNIQUE,
    id_DUAN INT,
    NgayKy DATE,
    GiaTri DECIMAL(15, 0) CHECK ( GiaTri >= 0 ),
    DieuKhoan VARCHAR(500),
    ChiTiet_HopDong TEXT,
    FOREIGN KEY (id_DUAN) REFERENCES DUAN(id) ON UPDATE CASCADE
);

-- Thay doi NgayThanhToan -> ThoiGianThanhToan
-- Thay Ten SoTien -> GiaTri
CREATE TABLE THANHTOAN (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaTT VARCHAR(20) NOT NULL UNIQUE,
    id_HOPDONG INT NOT NULL,
    ThoiGianThanhToan DATETIME DEFAULT CURRENT_TIMESTAMP,
    GiaTri DECIMAL(15, 0) CHECK ( GiaTri >= 0 ),
    FOREIGN KEY (id_HOPDONG) REFERENCES HOPDONG(id) ON UPDATE CASCADE
);

CREATE TABLE PHANCONG_DUAN (
	id_NHANVIEN INT,
    id_DUAN INT,
    id_VAITRO_DA INT, 
    SoGioDuKien MEDIUMINT UNSIGNED,
    NgayBatDau DATE,
    GhiChu VARCHAR(255),
    PRIMARY KEY (id_NHANVIEN, id_DUAN, id_VAITRO_DA),
    FOREIGN KEY (id_NHANVIEN) REFERENCES NHANVIEN(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_DUAN) REFERENCES DUAN(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_VAITRO_DA) REFERENCES VAITRO_DA(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Thay doi NgayMua -> ThoiGianMua
CREATE TABLE SUDUNG_VATTU (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaSDVT VARCHAR(20) NOT NULL UNIQUE,
    id_DUAN INT,
    id_DANHMUC_VATTU INT NOT NULL,
    SoLuongSuDung INT UNSIGNED,
    id_NHACUNGCAP INT,
    DonGiaApDung DECIMAL(15, 0) CHECK ( DonGiaApDung >= 0 ),
    ThoiGianMua DATETIME,
    FOREIGN KEY (id_DUAN) REFERENCES DUAN(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_DANHMUC_VATTU) REFERENCES DANHMUC_VATTU(id) ON UPDATE CASCADE,
    FOREIGN KEY (id_NHACUNGCAP) REFERENCES NHACUNGCAP(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Thay doi NgayLap -> ThoiGianLap
CREATE TABLE BAOCAO_TIENDO (
	id INT PRIMARY KEY AUTO_INCREMENT,
    MaBC VARCHAR(20) NOT NULL UNIQUE,
    id_DUAN INT NOT NULL,
    ThoiGianLap DATETIME NOT NULL,
    TyLeHT DECIMAL(5, 2) NOT NULL CHECK (TyLeHT >= 0 AND TyLeHT <= 100.00),
	MoTaNgan VARCHAR(255),
    GhiChu VARCHAR(500),
    FOREIGN KEY (id_DUAN) REFERENCES DUAN(id) ON DELETE CASCADE ON UPDATE CASCADE
);